version: "3.9"

services:
  db:
    image: postgres:16
    container_name: mealmate_db
    restart: always
    environment:
      POSTGRES_USER: mealmate_user
      POSTGRES_PASSWORD: mealmate_pass
      POSTGRES_DB: mealmate_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mealmate_user -d mealmate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
